<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeDebugSymbolsProjectOutputGroup>true</IncludeDebugSymbolsProjectOutputGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <Product>Llama.Memory</Product>
        <PackageId>Llama.Memory</PackageId>
        <Authors>nt153133</Authors>
        <PackageTags>memory-scanner, pattern-searcher, sigscan, pe-parser, portable-executable, reverse-engineering, binary-analysis, simd</PackageTags>
        <Description>Llama.Memory is a lightweight byte-pattern scanning and PE header utility library for .NET.</Description>
        <Company>LlamaMagic</Company>
        <Version>1.0.3</Version>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
